blank_issues_enabled: false

contact_links:
  - name: Telegram Forge-X Community
    url: https://t.me/+ihE2Ry8kBNkwYzhi
    about: Please join the community group
  - name: Discord FlashForge Community
    url: https://discord.gg/K7MH4hAfeX
    about: Join Discord server. Navigate to: Forums, mods-and-projects, Forge-X
